FROM node:alpine



# RUN mkdir /home/node/app
# WORKDIR /home/node/app
# COPY . /home/node/app
# RUN npm install --production

# CMD ["node", "dist/main.js"]
# EXPOSE 3000


WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build