version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: DockerFile
      args:
        - NODE_ENV=development
    environment:
      - OPEN_WEATHER_API_KEY= API-KEY-HERE
      - OPEN_WEATHER__BASE_URL=https://api.openweathermap.org/
      - CRON_INTERVAL= 0 0-23/1 * * *
      - MONGO_URL=mongodb://mongodb:27017/weather
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    command: npm run start:prod
    networks:
      - weather-network
  mongodb:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - weather-network

volumes:
  mongodb_data_container:

networks:
  weather-network: